#!/bin/bash
start=`date +%s` > /dev/null
red='\033[0;31m'
green='\033[0;32m'
yellow='\033[1;33m'
cyan='\033[1;36m'
clear='\033[0m'
white='\033[1;97m'

titles=(
"Star Wars: Episode I - The Phantom Menace"
"Star Wars: Episode II - Attack of the Clones"
"Star Wars: Episode III - Revenge of the Sith"
"Star Wars: The Force Awakens"
)
urlList=(
"https://es.megacdn.co:2228/v3-hls-playback/3bac6c96eb5259287df8719f3356168ded097e9a2bb2f4687cb899a855901dff40d12f52555c9155edb08982a05b48440129694686121bdaff6322e4bea1f9ece7953cba07f4dff53bdb20133a66781a5564a09a82a18bd54cbfb8604456e16c31841d0970a43fa3bc01003e941183d7d5ef7c32fddec3e4f91e0345309bd412d5593713e32f1fc1254f2b218c0633368ff603203cbd93bbfaeadaea1e5bbced660cac015ae459a28049bf0a25df1061/1080/index.m3u8"
"https://er.megacdn.co:2228/v3-hls-playback/4a995648884aa33ec4a1179328af845de80b2a6bf38776d2e33aa0c491d970fd4d764b8ea158822f0c5e18b5e0f4156d6d62e8bd6761dc6a6397cfc3124dc4eb619fe8e16fea4a23b858d868fbb79e52e9ab9072d4454bb8aa0318f5e2dadd92f06ce505ba5ca95faed4b0d1f668b5c28cbf640012e8b3cc76cb5c10f5c159c2844dc1de270b3523c0363d71aea9b037b8c8e1bf9f6b275f6f6a526b90435565e08e9bdf41860c4bf320a3e5b5caff37/1080/index.m3u8"
"https://eb.megacdn.co:2228/v3-hls-playback/d746a170e19ac28b3103f966b9faae8e2659437f59591af2a5552a3de3589a8175341db836f72986b54c3e1ee6d72192d4778ced8d6a89371b90261a797e25106e9514802aaed09ee1538fbea80e606b6d0a38260acf8bde57763d7571fccf9238a40ab4f4878453d6cf5a5f7627f22ca7db558c5c2aaab37d38f10c8674af5788456dc8f23b087cf629a438854befbdc925d66c3852f8d088eb6130bca30044b24b60c53fb24268a41c9bd0c2d7bad0/1080/index.m3u8"
"https://es.megacdn.co:2228/v3-hls-playback/daed7ef8741adeb05ab4c57e1e2f00a71b81fa4a5cdf01c7edac22185c0c374db8e35c40e77ce903df0975ff9a2410c93029f3b94ca1f9b5e3aec7537f3a1e23dee98179f45f47d97b4e4dbc4bd6e0e05d14f03d9102ac0fd98eb80917ab9be30b08086a42a398e84f30aee6bf4166f4918fe9baecf94a094fd1297ccb8c11f791f10ed294bdca7726d9b601fc61c5521a7b789f3b0010fcd1b80c77dc38ee9ea54b90be62041f64e8ba1cf3d4b9fd97/1080/index.m3u8"
)

x=0
errorCnt=0
url=""
mediaTitle=""
length=${#urlList[@]}
cnt=$length
((cnt--))
completedList=()
abortedList=()

trap ctrl_c INT

function ctrl_c () {
    { kill -9 $appID && wait; } 2>/dev/null
    { kill -9 $$ && wait; } 2>/dev/null
}

function sleepMode () {
    while /bin/true; do qdbus org.freedesktop.ScreenSaver /ScreenSaver SimulateUserActivity ; sleep 5m; done
}

ua="Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0"
# Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/567.36 (KHTML, like Gecko) Chrome/106.0.4495.0

options=( -q -c --progress --ignore-config --user-agent "$ua" --hls-prefer-native --no-check-certificate --socket-timeout 8 --no-warnings --concurrent-fragments 4 --retries 25 --fragment-retries 25 --abort-on-unavailable-fragments --retry-sleep 5 )

tempFile="/home/data/Movies/New/$mediaTitle.mp4"

function getMovie () {
        clear
        echo "Downloading $mediaTitle"
        while ! yt-dlp $url "${options[@]}" --format mp4 -o "$tempFile"; do
            ((errorCnt++));
            if (( errorCnt > 25)); then
                abortedList+=("$mediaTitle");
                break;
            else
                sleep 5;
            fi
        done;
        if ffmpeg -v quiet -y -i "$tempFile" -metadata title="$mediaTitle" -codec copy "/home/data/Movies/$mediaTitle.mp4"; then
            rm "$tempFile";
            rm -f /home/data/Movies/New/*.temp
            completedList+=("$mediaTitle");
        fi
}

sleepMode &
appID=$!

for (( i=0; i < ${length}; i++ )) do
    url="${urlList[$i]}";
    mediaTitle="${titles[$i]}";
    errorCnt=0;
    getMovie;
    if (( ${cnt} == i )); then  ## skip sleep last iteration
        sleep 1
        clear
    else
        sleep 5m
    fi
done
ftime=`date +"%m-%d-%Y %l:%M %P"`
echo " "
echo -e "${yellow}************************************************************************************${clear}"
echo -e "Duration: $((($(date +%s)-$start)/60)) minutes"
if (( ${#completedList[@]} > 0)); then
    echo -e "Completed Downloads: $ftime${white}"
    printf '\t%s\n' "${completedList[@]}"
    echo -e "${clear}"
fi
if (( ${#abortedList[@]} > 0)); then
    echo -e "${red}Aborted Downloads:${white}"
    printf '\t%s\n' "${abortedList[@]}"
    echo -e "${clear}Check Temp Folder..."
fi
echo -e "${yellow}************************************************************************************${clear}"
ctrl_c
