#!/bin/bash
# plasmaVer=`plasmashell -v | cut -c 13-`
title="[General]\n"
name="Name=Plasma OS\n"
logo="LogoPath=/home/matt/Pictures/Misc/icons/intel.png\n"
web="Website=https://github.com/txhammer68\n"
osVer=`lsb_release -r | tr '\n' ' '| tr '\t' ' ' | cut -c 10- | sed 's/[ \t]*$//'` >/dev/null
# CODE=`lsb_release -c | tr '\n' ' '| tr '\t' ' ' | cut -c 11- | sed 's/[ \t]*$//'`>/dev/null
# DISTRO=`lsb_release -d | tr '\n' ' '| tr '\t' ' ' | cut -c 14- | sed 's/[ \t]*$//'`>/dev/null
version="Version=$osVer\n"
var="Variant=Digitech Edition\n"
echo -e "$title$name$logo$web$version$var" > /home/matt/.config/kcm-about-distrorc
